name: 'Buildah Action'
description: 'This action allows you to build an image from your app'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'The name (reference) of the image to build'
    required: true
  base-image:
    description: 'The base image to use to create a new container image'
    required: false
  dockerfiles:
    description: 'List of Dockerfile paths (eg: ./Dockerfile)'
    required: false
  context:
    description: 'Path to the directory to use as context (default: .)'
    required: false
    default: '.'
  content:
    description: 'List of files/directories to copy inside the base image'
    required: false
  entrypoint:
    description: 'The entry point to set for containers based on image'
    required: false
  port:
    description: 'The port to expose when running containers based on image'
    required: false  
  working-dir:
    description: 'The working directory to use within the container'
    required: false
  envs:
    description: 'List of environment variables to be set when running containers based on image'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'